### ISSUE TITLE
Example to work on Windows?

### ISSUE THREAD

**Issue by KerstinKeller** [forexample/hunter-simple#2]
I am trying to get this example to work on Windows with CMake and VS2012, but recieve a lot of build errors when hunter tries to build GTest. They seem mostly template based errors, just like

``` Bash
h:\.hunter\_Base\a63185b\87cd7ec\200081a\Build\GTest\Source\include\gtest/internal/gtest-param-util-generated.h(5103): error C3203: 'tuple' : unspecialized class template can't be used as a template argument for template parameter 'T', expected a real type [H:\.hunter\_Base\a63185b\87cd7ec\200081a\Build\GTest\Build\GTest-prefix\src\GTest-build\gtest.vcxproj] [h:\.hunter\_Base\a63185b\87cd7ec\200081a\Build\GTest\Build\GTest.vcxproj]
```

Is this example supposed to work on Windows, or are there any workarounds?

**Comment by KerstinKeller** [comment]
Sorry for the hassle, this actually seems to be a GTest / VS2012 problem rather than a hunter problem. The lastest GTest version cannot be build with VS2012 out of the box.

**Comment by ruslo** [comment]
@KerstinKeller Thanks for the report. The problem was about `_VARIADIC_MAX` which is not specified as a requirement. See fix: https://github.com/hunter-packages/gtest/commit/0fc0224d55bbb5c8c89629a9c3b2f58f4118afa7

Hunter with new GTest version (see branch `develop`): https://github.com/forexample/hunter-simple/commit/1e0a573901291dd626880074bf657f42d62eb101

**Comment by KerstinKeller** [comment]
Perfect, works for me! Thanks for the fast reply / fix.
